FROM python:3.13-slim-bookworm

WORKDIR /

# System dependencies
RUN pip install --upgrade pip

# Install Python dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

EXPOSE 444

CMD ["gunicorn", "main:app", "-b", "0.0.0.0:444", "--certfile", "/certs/localhost.com+4.pem", "--keyfile", "/certs/localhost.com+4-key.pem"]