CREATE TABLE TRANSACTIONS (
    TRANSACTION_ID INTEGER IDENTITY(1,1) PRIMARY KEY,
    ACCOUNT_ID INTEGER NOT NULL FOREIGN KEY REFERENCES ACCOUNTS(ACCOUNT_ID),
    CATEGORY VARCHAR(50) NOT NULL,
    AMOUNT REAL NOT NULL DEFAULT 0.0 CHECK (AMOUNT >= 0),
    TRANSACTION_TYPE VARCHAR(50) NOT NULL CHECK (TRANSACTION_TYPE IN ('DEBIT', 'CREDIT')),
    TRANSACTION_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PAID BOOLEAN,
    DESCRIPTION VARCHAR(255)
);